version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:containerizeddatabasegalore@mypostgres:5432/assignment_data
    networks:
      - ff_network
    depends_on:
      mypostgres:
        condition: service_healthy  # Wait for PostgreSQL to be healthy

  mypostgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: containerizeddatabasegalore
      POSTGRES_DB: assignment_data
    networks:
      - ff_network
    ports:
      - "5432:5432"  # Optional: Expose PostgreSQL port
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ff_network:
    driver: bridge
